### ISSUE TITLE
downloadURL 與 updateURL 不能刪掉

### ISSUE THREAD

**Issue by pthuang01** [moontai0724/bahamut-sign-helper-script#3]
updateURL 是用來檢查 metadata 是否有新版本
downloadURL 是用來在有更新版本的時候指定下載位置
這兩個項目都是原本就存在的
我只是加上了空白讓它縮排齊頭而已
這東西不應該刪掉
否則一般使用者的腳本會無法自動更新

或者更進一步說
已經更新過腳本的使用者，現在已經無法再自動更新了........
（因為新的版本已經刪除了這個部份，他們已經無法再發現有後續更新了  囧"）

**Comment by moontai0724** [comment]
Hi pthuang01~

別這麼擔心～`downloadURL` & `updateURL` 本來就不在原始碼裡面，正如我所說，他們會被 GreasyFork (也就是這個腳本使用的發布網站) 加上去，你使用的 script engine (像是 Tamper Monkey) 也通常會自己記錄下載的來源位置。

舉例來說，你可以看到發布新版後的[下載連結](https://update.greasyfork.org/scripts/36964/%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9%E8%87%AA%E5%8B%95%E7%B0%BD%E5%88%B0%EF%BC%88%E5%90%AB%E5%85%AC%E6%9C%83%E3%80%81%E5%8B%95%E7%95%AB%E7%98%8B%EF%BC%89.user.js)裡面也還是有這些網址，[每日檢查更新量](https://greasyfork.org/zh-TW/scripts/36964-%E5%B7%B4%E5%93%88%E5%A7%86%E7%89%B9%E8%87%AA%E5%8B%95%E7%B0%BD%E5%88%B0-%E5%90%AB%E5%85%AC%E6%9C%83-%E5%8B%95%E7%95%AB%E7%98%8B/stats#update-check-stats-chart-container)也還很正常。

如果你詳細看你的 commit，你也可以看到這兩行是你新增的: https://github.com/moontai0724/bahamut-sign-helper-script/commit/62830c404e6164ce2f8cec709ded2acceb4b3e78#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR22-R23

所以使用者還是可以正常收到更新哦～別擔心 XD

**Comment by pthuang01** [comment]
原來如此，是我草率了 @@
感謝說明~
